### ISSUE TITLE
Allow annotations on packages / package-info?

### ISSUE THREAD

**Issue by jhorstmann** [whiskeysierra/archer#11]
This would avoid cluttering all classes with annotations and maybe also avoids having different concerns in the same package. The question is if these can be used in aspects, especially if subpackages are also used.

**Comment by whiskeysierra** [comment]
Quote from the [official AspectJ docs](https://eclipse.org/aspectj/doc/next/adk15notebook/annotations-pointcuts-and-advice.html#package-and-parameter-annotations):

> Package and Parameter Annotations

> Matching on package and parameter annotations is not supported in AspectJ 1.5.0. Support for this capability may be considered in a future release.

I'd love to have this, but since we can't enforce it right now with an aspect it would be nothing else but a comment, which will be ignored by developers.
